// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2XQkqUrqDc9ui4eDKlEPVBIcXwz9thUQ',
    appId: '1:680669654381:web:11a7499c0fa1c204e9be64',
    messagingSenderId: '680669654381',
    projectId: 'tech-saude',
    authDomain: 'tech-saude.firebaseapp.com',
    storageBucket: 'tech-saude.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfXUn-4cZnKTGp1K2AR15pTKKsvJbwFT4',
    appId: '1:680669654381:android:d453cbb285324001e9be64',
    messagingSenderId: '680669654381',
    projectId: 'tech-saude',
    storageBucket: 'tech-saude.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaBys96skj_Fr9FsPcWY4o2QDUXZ4YhsQ',
    appId: '1:680669654381:ios:340037d317dce1a3e9be64',
    messagingSenderId: '680669654381',
    projectId: 'tech-saude',
    storageBucket: 'tech-saude.appspot.com',
    androidClientId: '680669654381-3fs5ftmmflnpg4kia571o5l0r460hpng.apps.googleusercontent.com',
    iosClientId: '680669654381-2er7h5ne88kmd9vocbc2o2tn642veokg.apps.googleusercontent.com',
    iosBundleId: 'com.example.saudeTech',
  );
}
